name: GitHub-Profile-3D-Contrib

on:
  push:
    branches: [main]
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        with:
          USERNAME: NatanOliveiraslv
          THEME: github
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
